### ISSUE TITLE
Calculate Warren-Cowley short-range-order

### ISSUE THREAD

**Issue by QQQsupermans** [dgehringer/sqsgenerator#14]
Hi, 
I have a queation about short-range-order (SRO) when I use your code "sqsgenerator-fix-alpha-command".  Taking Ni3Al (L12) as an example. The POSCAR file like this.

_# Ni Al L12
3.0
1.0000000000         0.0000000000         0.0000000000
0.0000000000         1.0000000000         0.0000000000
0.0000000000         0.0000000000         1.0000000000
Al Ni
1 3
D
0.0  0.0  0.0
0.5  0.5  0.0
0.5  0.0  0.5
0.0  0.5  0.5_

I use the command "sqsgenerator alpha sqs POSCAR --weight=1 --verbosity=3", and the result is as follows,
α=1.8888888888888888
α[Al-Al]=1.00000000000000
α[Al-Ni]=-0.33333333333333
α[Ni-Ni]=0.55555555555556

The SRO of Ni-Ni does not agree with theoretical result (i.e. 1/9). In addition, I test the SRO of pure Ni (fcc), and the vaule is 0.5. I hope to calculate SRO of multi-component alloys. Whether the SRO of A-B bond should be ignored when A and B are the same element?

Thank you!

**Comment by dgehringer** [comment]
The reason why the the value is wrong is that the computation of the occupations of the coordination shells is "*wrong*".

The programm basically creates a histogramm of the distance matrix, to determine how many atoms are in the individual coordination shells. As in this small cell there are only 4 atoms, all the other three atoms are in the first coordination shell. Therefore, we get with 3 Ni-Ni bonds, α=1 - 3/(4 * 3 * (3/4)^2) = 1 - 4/9 = 5/9 = 0.55555555559. This is how we get to this wrong answer.

The reason why that is so is that, we usually deal with super-cells where this case does never happen (for us at least).

> By the way, how to cite your code? Have you published papers by using this code.

Actually not yet! I'm working on it! I'm intensively working on a new version of it where I want to fix all those problems

**Comment by QQQsupermans** [comment]
In other words, this code can correctly deal with the short-range order of A-B bonds when A and B are different, is it right?

**Comment by dgehringer** [comment]
> For Ni3Al, I use 108-atom (3 * 3 * 3) supercell, and the result is same.

Indeed I can confirm that

> I think the difference may be due to the formula. The theoretical SRO formula is α=1-(Pij/Cj), where Pij is probability of j around i atom, and Cj is concentration of j. Taking 1st nearest neighbor as an example.
(1) For pure Ni (fcc), the theoretical SRO is 1-1/1=0. For your formula, the SRO of Ni-Ni is α=1-(12/2 N)/(N * 12 * 1 * 1)=0.5.
(2) For Ni3Al (L12), the theoretical SRO of Ni-Ni is 1-(2/3)/(3/4)=1/9. For your formula, the SRO of Ni-Ni is α=1-3N/(N * 12 * 0.75 * 0.75)=5/9. There are 6N bonds in Ni3Al (L12), 3N for Ni-Al, and 3N for Ni-Ni.

I also double checked that. Tt seems that you were right! I do get one half for the pure systems
So I have to correct myself as it seems the the computation of the shell occupation is alright, and the difference comes from, as you already said, the different definition
