### ISSUE TITLE
Issue with ASE structure conversion

### ISSUE THREAD

**Issue by abuanand** [dgehringer/sqsgenerator#35]
Hi,
I was trying to use the sqs_analyse function using an ASE Atoms object.

` from ase.io import read
from sqsgenerator.public import sqs_analyse

ase_struct = read('converted.cfg')
sqs_analyse(ase_struct,structure_format='ase') `

This returns
` File "/home/abuanand/miniconda3/lib/python3.8/site-packages/sqsgenerator/adapters.py", line 95, in from_ase_atoms
    lattice = np.array(atoms.cell)
AttributeError: 'Atom' object has no attribute 'cell'`

Although, `np.array(ase_struct.cell)` returns the cell dimensions properly. 

Any input on this would be great. Thanks for your help!

**Comment by dgehringer** [comment]
Dear @abuanand !

Many thanks for your error report, however, I'd need some more input to reproduce the error!
Strangely, the [current documentation](https://wiki.fysik.dtu.dk/ase/_modules/ase/atoms.html#Atoms) also defines such a property. As you already pointed out!

1.) Which version of `ase` are you using?
You can figure it out using `sqsgen --version ` which will print a line which looks like this

```python
    modules: ('ase-3.22.1', 'rich', 'json', 'yaml-6.0', 'pickle')
```

2.) Please attach the your file *converted.cfg* to this issue

That will make it much easier for me to figure out what's going on

**Comment by dgehringer** [comment]
But before that, maybe give this a try the following:

The `sqs_analyse` functions expects an `Iterable[Structure]` as its first argument. You can find this here in the [documentation](https://sqsgenerator.readthedocs.io/en/latest/api_reference.html#sqsgenerator.public.sqs_analyse).

Thus maybe just slightly adapting the second line of your code to 

```python
sqs_analyse([ase_struct], structure_format="ase") 
```

already fixes your problem!

Best regards

**Comment by abuanand** [comment]
Hi @dgehringer 
Passing the Atoms object as an iterable object does the trick. 
Thanks
