### ISSUE TITLE
Number of A-B bonds for (111)-oriented supercells of N3Al

### ISSUE THREAD

**Issue by QQQsupermans** [dgehringer/sqsgenerator#36]
Hi!
    I highly appreciate your help. I have a question now. I want to test the number of Ni-Al and Al-Al bonds of (111)-oriented supercells, so that for further investigations of planar faults. This supercell has 18 Al and 54 Ni atoms. Theoretically, there are 72*3=216 Ni-Ni bonds and 216 Ni-Al bonds.  
    However, when I use "sqsgen analyse POSCAR --settings yaml", the result shows that the numbers Ni-Ni is only 198. That is to say, 216-198=18 Ni-Ni bonds are missing. This error has nothing to do with the deviations from the perfect lattice. I don't know why.  The screenshot, yaml file and POSCAR are attached as follows:

screenshot file
![image](https://user-images.githubusercontent.com/92912876/224382394-a9eb9380-be4f-45da-91b0-b9a0433ccd9b.png)

yaml file:
rtol: 0.05
shell_weights:
  1: 1.0
prefactor_mode: set
prefactors: -1

POSCAR file:
Ni3Al-POSCAR           
1.0
        5.0463247299         0.0000000000         0.0000000000
        0.0000000000         8.7521600723         0.0000000000
        0.0000000000         0.0056848720        18.5539599293
   Ni   Al
   54   18
Cartesian
     1.261581483         6.564122170         0.000094803
     3.784744450         2.188042134         0.000094888
     1.261584942         0.729883473         2.061565357
     3.784748059         5.105963770         2.061565495
     1.261571482         3.648053724         4.123167485
     3.784734223         8.024133760         4.123167485
     1.261584190         6.566021302         6.184752472
     3.784746555         2.189940744         6.184753025
     1.261587649         0.731832860         8.246367595
     3.784748661         5.107913026         8.246368148
     1.261575768         3.649937769        10.307960600
     3.784736329         8.026017283        10.307959494
     1.261579378         6.567909531        12.369580146
     3.784740840         2.191828582        12.369581252
     1.261593515         0.733707900        14.431141079
     3.784755579         5.109787676        14.431142185
     1.261575016         3.651882305        16.492678789
     3.784737532         8.027962341        16.492677683
     1.261580280         2.188042134         0.000094883
     3.784743247         6.564122170         0.000094686
     1.261576821         5.105963770         2.061565495
     1.261590507         8.024133760         4.123167485
     3.784739938         0.729883407         2.061565357
     3.784753173         3.648053724         4.123167762
     1.261578250         2.189940744         6.184753025
     3.784740540         6.566021302         6.184752472
     1.261575919         5.107912505         8.246368148
     1.261588251         8.026017805        10.307959494
     3.784736930         0.731832729         8.246367595
     3.784748962         3.649937769        10.307959494
     1.261583890         2.191828582        12.369581252
     3.784745352         6.567909531        12.369580146
     1.261569226         5.109788197        14.431142185
     1.261587198         8.027962341        16.492677683
     3.784731215         0.733707965        14.431141079
     3.784749563         3.651882305        16.492678789
     0.000000000         4.376083195         0.000092964
     2.523162365         0.000002327         0.000093686
     0.000000000         7.294003269         2.061575448
     2.523162365         2.917923755         2.061575448
     0.000000000         1.460001056         4.123169144
     2.523162365         5.836082266         4.123168591
     0.000000000         4.377977630         6.184746390
     2.523162365         0.001898301         6.184746390
     0.000000000         7.295961914         8.246371466
     2.523162215         2.919882138         8.246370913
     0.000000000         1.461890056        10.307957282
     2.523162215         5.837971005        10.307957282
     0.000000000         4.379868994        12.369588993
     2.523162215         8.755947987        12.369588993
     0.000000000         7.297846473        14.431138868
     2.523162365         2.921765393        14.431138868
     0.000000000         1.463836677        16.492671048
     2.523162365         5.839916061        16.492671048
     0.000000000         0.000001526         0.000090592
     2.523162365         4.376082150         0.000089676
     0.000000000         2.917811375         2.061706913
     2.523162365         7.293891151         2.061707466
     0.000000000         5.836245042         4.123219186
     0.000000000         0.001899484         6.184636906
     2.523162365         1.460164093         4.123220016
     2.523162365         4.377978119         6.184638011
     0.000000000         2.919846372         8.246265852
     2.523162365         7.295926409         8.246268617
     0.000000000         5.837996072        10.308044648
     0.000000000         8.755930294        12.369732760
     2.523162064         1.461914992        10.308044648
     2.523161914         4.379850518        12.369731655
     0.000000000         2.921561415        14.431122279
     2.523162215         7.297642495        14.431122279
     0.000000000         5.840060524        16.492543869
     2.523162365         1.463980879        16.492542763

**Comment by QQQsupermans** [comment]
The result of (0 1 0)-oriented supercells is right. However, I have the same problem when I use (2 1 0)-oriented supercells. The 40-atom supercells should have 40*3=120 Ni-Al bonds. The screenshot, yaml file and POSCAR are attached as follows:

The screenshot file:
![image](https://user-images.githubusercontent.com/92912876/224462545-d361e240-9135-40bb-b83a-7938fea55565.png)

yaml file:
rtol: 0.05
shell_weights:
1: 1.0
prefactor_mode: set
prefactors: -1

POSCAR file:
Ni3Al-POSCAR-(2 1 0)
3.569
        1.0000000000         0.0000000000         0.0000000000
        0.0000000000         2.2360999584         0.0000000000
        0.0000000000         0.0000000000         4.4720997810
   Al   Ni
   10   30
Direct
     0.000000000         0.000000000         0.000000000
     0.000000000         0.600000024         0.100000001
     0.000000000         0.200000003         0.200000003
     0.000000000         0.800000012         0.300000012
     0.000000000         0.400000006         0.400000006
     0.000000000         0.000000000         0.500000000
     0.000000000         0.600000024         0.600000024
     0.000000000         0.200000003         0.699999988
     0.000000000         0.800000012         0.800000012
     0.000000000         0.400000006         0.899999976
     0.500000000         0.500000000         0.000000000
     0.500000000         0.100000001         0.100000001
     0.500000000         0.699999988         0.200000003
     0.500000000         0.300000012         0.300000012
     0.500000000         0.899999976         0.400000006
     0.500000000         0.500000000         0.500000000
     0.500000000         0.100000001         0.600000024
     0.500000000         0.699999988         0.699999988
     0.500000000         0.300000012         0.800000012
     0.500000000         0.899999976         0.899999976
     0.000000000         0.300000012         0.050000001
     0.000000000         0.899999976         0.150000006
     0.000000000         0.500000000         0.250000000
     0.000000000         0.100000001         0.349999994
     0.000000000         0.699999988         0.449999988
     0.000000000         0.300000012         0.550000012
     0.000000000         0.899999976         0.649999976
     0.000000000         0.500000000         0.750000000
     0.000000000         0.100000001         0.850000024
     0.000000000         0.699999988         0.949999988
     0.500000000         0.800000012         0.050000001
     0.500000000         0.400000006         0.150000006
     0.500000000         0.000000000         0.250000000
     0.500000000         0.600000024         0.349999994
     0.500000000         0.200000003         0.449999988
     0.500000000         0.800000012         0.550000012
     0.500000000         0.400000006         0.649999976
     0.500000000         0.000000000         0.750000000
     0.500000000         0.600000024         0.850000024
     0.500000000         0.200000003         0.949999988

**Comment by dgehringer** [comment]
Hi many thanks for your report. I will have a look into it

**Comment by QQQsupermans** [comment]
I really appreciate all your help! I am still checking the results. In addition, I use Ovito software to check the bond number of the first POSCAR. The number is also 216*2=432, which shows as follows.  I'm not sure what causes the different result. If I find the reason, I will send it to you. 
![image](https://user-images.githubusercontent.com/92912876/235640425-c071115e-34c3-424d-91ef-815fcfce6b9c.png)
