### ISSUE TITLE
Valueerror on unspecified file (here: POSCAR)

### ISSUE THREAD

**Issue by ndhamrai** [dgehringer/sqsgenerator#39]
I have the following raised value error: raise ValueError(f"Format not specified and could not infer from {filename=}")
ValueError: Format not specified and could not infer from filename='poscar'

when running the sqsgenerator with: "sqsgen run iteration -e -f poscar -c xz -w pymatgen" like in the doc or a modified one for my purpose (sqsgen run iteration -e -w pymatgen -f poscar -di objective -di parameters $workdir/$SYSTEM.yaml)

Although pymatgen and ase are updated to latest versions. Is there any approach, how to solve this issue?

Thanks in advance

**Comment by dgehringer** [comment]
Hi @ndhamrai!

Can you provide me with a slightly longer and more detailed stack trace? And maybe share the input file with me so that I can reproduce the error?

**Comment by ndhamrai** [comment]
Hi @dgehringer,

sure. I provide the stdout file containing the stack trace with the error + my input file. 
[sqsgen.zip](https://github.com/dgehringer/sqsgenerator/files/13426655/sqsgen.zip)

**Comment by dgehringer** [comment]
Thanks a lot
