### ISSUE TITLE
setting up the composition flag correctly

### ISSUE THREAD

**Issue by johwag** [dgehringer/sqsgenerator#4]
Hi!
I am trying to use sqsgenerator for a binary alloy with varying composition.
I have an AxBx-1 tetragonal alloy and would like to generate SQS for different x. 
e.g. x=0.25 x=0.33 and so on.
There are 12 sites in the unit cell.

I have a POSCAR for all different x, looking something like this
 vasp
 1.00000000
  5.928100    0.000000    0.000000
  0.000000    5.928100    0.000000
  0.000000    0.000000    6.980300
 A B
  9 3
 Direct
 _positions_

I would like to mix on all the positions and look for the SQS for each x

I guess the syntax would be something like: 
sqsgenerator POSCAR 2 2 2 A:0.75,B:0,25

for the above example of x=0.75, is that correct? or am I missing something?

**Comment by dhoulek** [comment]
Hi,

Yes, that seems almost correct: 
* you haven't specified the type of sqs required
* there is comma instead of dot in your B composition.

sqsgenerator sqs POSCAR 2 2 2 A:0.25,B:0.75

David
