### ISSUE TITLE
In using the API for SRO analysis, the SRO results are greater than 1

### ISSUE THREAD

**Issue by nanoparticals** [dgehringer/sqsgenerator#45]
I would like to seek your help; the structure I analyzed has an SRO close to 1.25, but theoretically, it should be between -1 and 1. Where might the problem lie?The Objective results are around 10. I am conducting high-throughput screening of quinary high-entropy oxides. Is this Objective result too large? I would be grateful for your advice.
'parameters': array([[[  1.        ,  -1.25      ,  -1.25      ,  -1.25      ,
          -1.25      ],
        [ -1.25      ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [ -1.25      ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [ -1.25      ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [ -1.25      ,   1.        ,   1.        ,   1.        ,
           1.        ]],

       [[ -0.125     ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [  1.        ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [  1.        ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [  1.        ,   1.        ,   1.        ,   1.        ,
           1.        ],
        [  1.        ,   1.        ,   1.        ,   1.        ,
           1.        ]],

 Filename  Objective
0     107373442.cif   7.965926
1      86197291.cif  10.085185
2      53823169.cif  12.567407
3     121659148.cif   9.729630
4     134814692.cif   9.840741
...             ...        ...
8877  122649240.cif   9.840741
8878   83395349.cif  10.085185
8879   87580707.cif   7.740000
8880  376447814.cif   7.965926
8881   28984430.cif   8.892000

[8882 rows x 2 columns]

**Comment by dgehringer** [comment]
Hi @nanoparticals!

Can you share the input lattice/structure and the exact settings you pass to the API with me? Otherwise it is impossible to reproduce the potential error

**Comment by nanoparticals** [comment]
[IrO22.txt](https://github.com/user-attachments/files/16655112/IrO22.txt)

Of course, I would be very grateful for your reply. This is my original unit cell. I hope to replace the Ir atoms with five different metals, with the Ir and Ru elements remaining unchanged while only the other three elements are altered. This will complete the construction of the high-entropy oxide.
# Configure the SQS optimization parameters and generate the structure object
def generate_sqs_structures(structure_file, supercell, iterations, shell_weights, elements, combinations, ratios):
#Read the base structure
    pymatgen_structure = PymatgenStructure.from_file(structure_file)
    base_structure = Structure(lattice=pymatgen_structure.lattice.matrix, 
                               frac_coords=pymatgen_structure.frac_coords, 
                               symbols=[site.species_string for site in pymatgen_structure], 
                               pbc=(True, True, True))
    
    # Find the indices of all Ir atoms
    ir_indices = [i for i, symbol in enumerate(base_structure.symbols) if symbol == 'Ir']
    num_ir_atoms = len(ir_indices)

    for ratio in ratios:
        if rank == 0:
            print(f"Processing ratio: {ratio}")
        for combination in combinations:
            if rank == 0:
                print(f"Combination: {combination}")
            total_atoms = 48  # Total number of atoms is 48
            o_atoms = 32  # Number of oxygen atoms is 32
            metal_atoms = total_atoms - o_atoms  # Total number of metal atoms

            composition = {'Ir': int(np.round(ratio[0] * metal_atoms)), 'Ru': int(np.round(ratio[1] * metal_atoms)), 'O': o_atoms}
            for i, elem in enumerate(combination):
                composition[elem] = int(np.round(ratio[i + 2] * metal_atoms))
            
            # Adjust to ensure the total number of atoms matches
            total_composition_atoms = sum(composition.values()) - o_atoms
            if total_composition_atoms != metal_atoms:
                # Adjust the quantity of the last element to match the total number of atoms.
                last_elem = combination[-1]
                composition[last_elem] += metal_atoms - total_composition_atoms
            
            if rank == 0:
                print(f"Combination: {combination}, Ratio: {ratio}, Composition: {composition}")

            # Replace Ir atoms
            new_species_for_replacement = ['Ir'] * composition['Ir'] + ['Ru'] * composition['Ru']
            for elem in combination:
                new_species_for_replacement += [elem] * composition[elem]
            
            # Ensure the length of new_species_for_replacement matches the length of Ir_indices
            new_species_for_replacement = new_species_for_replacement[:len(ir_indices)]
            
            #Replace Ir atoms using slice_with_species
            new_structure = base_structure.slice_with_species(new_species_for_replacement, ir_indices)
            
          #Generate the SQS (Special Quasi-Regular) structure
            configuration = {
                'structure': new_structure,
                'supercell': supercell,
                'iterations': iterations,
                'shell_weights': shell_weights,
                'elements': elements
            }
          The above is the process I use to generate the high-entropy oxide SQS (Special Quasi-Regular) structure. During the structure generation, the oxygen atoms disappear, so what is generated is an SQS structure consisting only of quinary metals. I analyze these structures.
import os
from pymatgen.io.cif import CifParser
import pandas as pd
from sqsgenerator.public import sqs_analyse

def analyse_cif_files_in_directory(directory):

    data = []


    for filename in os.listdir(directory):
        if filename.endswith('.cif'):
            cif_file_path = os.path.join(directory, filename)
            parser = CifParser(cif_file_path)
            structures = parser.parse_structures()


            results = sqs_analyse(structures, structure_format='pymatgen')

  
            for result in results.values():
                objective_value = result.get('objective', None)
                if objective_value is not None:
                    data.append({'Filename': filename, 'Objective': objective_value})


    df = pd.DataFrame(data)
    return df


directory_path = '/home/haoxw/MEOwork/Calculate_dir/SQS/'
df = analyse_cif_files_in_directory(directory_path)
print(df)
Results are as follows:           
Filename  Objective
0     107373442.cif   7.965926
1      86197291.cif  10.085185
2      53823169.cif  12.567407
3     121659148.cif   9.729630
4     134814692.cif   9.840741
...             ...        ...
8877  122649240.cif   9.840741
8878   83395349.cif  10.085185
8879   87580707.cif   7.740000
8880  376447814.cif   7.965926
8881   28984430.cif   8.892000

[8882 rows x 2 columns]

**Comment by dgehringer** [comment]
Hi @nanoparticals!

I have to more questions!

While in principle you are absolutely right that the $|\alpha_{ij}| \geq 1$. However, there might be some caveates, especially if there are multiple sublattices involoved

Basically in you input structure you have to sublattices the metal and the oxygen sublattice. And if I understand it correctly, you only want to decorate the metal sublattice.

Do you care about the oxygen sublattice? More precisely, do you care about Metal - Oxygen bonds? Do you want to optimize them?
 In your problem report the Metal - Oxygen SRO $\alpha_{\text{Me}\text{O}} \approx 1.25$ I think that is causing the problem.

Or do you consider only the metal sublattices as a solid solution?

**Comment by nanoparticals** [comment]
Yes, just as you mentioned, my issue has been resolved. Thank you very much for your help!
