### ISSUE TITLE
`numpy.float128` not available on Windows

### ISSUE THREAD

**Issue by realitychemist** [dgehringer/sqsgenerator#46]
Attempting to run the latest version of sqsgenerator on Windows 10 (64-bit) gives the following error upon the completion of a simulation: `AttributeError: module 'numpy' has no attribute 'float128'. Did you mean: 'float16'?` Here's the full traceback (paths trimmed to site-packages):

```Traceback (most recent call last):
  File "...\sqsgen\Scripts\sqsgen-script.py", line 10, in <module>
    sys.exit(cli())
             ^^^^^
  File "...\click\core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\click\core.py", line 1078, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "...\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\click\core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\click\core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\click\core.py", line 783, in invoke
    return __callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\sqsgenerator\commands\common.py", line 88, in _inner 
    result = f(*args, **kwargs)
             ^^^^^^^^^^^^^^^^^^
  File "...\sqsgenerator\commands\common.py", line 132, in _dummy
    return f(settings, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "...\sqsgenerator\commands\run.py", line 44, in iteration 
    to_dict(final_document), output_format=dump_format
    ^^^^^^^^^^^^^^^^^^^^^^^
  File "...\sqsgenerator\io.py", line 288, in to_dict
    np.float128: float,
    ^^^^^^^^^^^
  File "...\numpy\__init__.py", line 414, in __getattr__
    raise AttributeError("module {!r} has no attribute "
AttributeError: module 'numpy' has no attribute 'float128'. Did you mean: 'float16'?
```

Just searching around a little bit online, it looks like `numpy.float128` is unavailable on Windows and Mac (at least M1, maybe also M2). I re-ran the script on the same machine but under WSL (Debian) and it completed without errors. I got a well-formatted `*.result.yaml` file that I was able to export as a `.cif`. So this appears to be an issue on non-linux operating systems only.

The simple fix would seem to be just exporting with float-64 precision instead: [this discussion](https://stackoverflow.com/questions/29820829/cannot-use-128bit-float-in-python-on-64bit-architecture) suggests that even where the name `numpy.float128` is available it is probably not actually giving 128 bits of precision, so just changing the output to float64 seems like it might be fine. Otherwise you could test for float128 support before exporting, and export with float64 only if it's not available.

**Comment by dgehringer** [comment]
Hi @realitychemist !

Thanks a lot for digging that deep! 
Indeed it is true that wide integer types are missing on Windows! 
Actually we also need those types to generate random numbers. Therefore, there's already a Windows specific workaround

https://github.com/dgehringer/sqsgenerator/blob/cc81881574776e1d41ea16585e0e6fd3bc7ca719/sqsgenerator/core/python/CMakeLists.txt#L33

But that should be easy to fix!

Thanks again for reporting and for helping so much

Best
@dgehringer

**Comment by realitychemist** [comment]
Thank you for the reply! Does this mean I should be building from source instead of installing the pre-built version that lives on conda-forge in order to get this working on Windows? Or did I misunderstand this?

**Comment by dgehringer** [comment]
Sorry for my unclear communication on that point!

You should be able to use the conda-forge binaries. It's just that it takes some time until the changes are available with conda, but I have already triggered rebuilding of the package (https://github.com/conda-forge/sqsgenerator-feedstock/pull/48)

The CI has finished so the packages should be available within a few hours from now

**Comment by realitychemist** [comment]
Oh I see! Thank you for the response, that was my misunderstanding. It does look like the new version is already on conda-forge by the time I'm writing this. I've just tested it and it works in Windows without any errors now, all the way up through exporting .cif files. Thank you for the very quick fix!

**Comment by dgehringer** [comment]
Thanks a lot for your feedback
